apiVersion: v1
kind: Service
metadata:
  name: ubuntu-debug-service
  labels:
    service: ubuntu-debug-service
spec:
  type:
  selector:
    app: ubuntu-debug-a
  ports:
  - port: 5000
    targetPort: 5000
