apiVersion: apps/v1
kind: Deployment
metadata:
    name: ubu
spec:
    selector:
        matchLabels:
            app: ubu
    replicas: 1
    template:
        metadata:
            labels:
                app: ubu
        spec:
            containers:
            - name: ubu
              image: ubuntu
              ports:
                - containerPort: 5000
              command: ["/bin/sleep", "3650d"]
