apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ubuntu-debug-role-binding
subjects:
- kind: ServiceAccount
  name: spinupcontainers
  namespace: default
roleRef:
  kind: Role
  name: ubuntu-debug-role
  apiGroup: rbac.authorization.k8s.io
