apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone-meta-controller-role
  namespace: default
  labels:
    app: drone-meta-controller-role
rules:
- apiGroups: [""]
  resources:
  - deployments
  - pods
  - services
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - watch
  - list