apiVersion: apps/v1
kind: Deployment
metadata:
    name: prometheus-tst-reporter
spec:
    selector:
        matchLabels:
            app: prometheus-tst-reporter
    replicas: 1
    template:
        metadata:
            labels:
                app: prometheus-tst-reporter
            annotations:
              prometheus.io/scrape: 'true'
              prometheus.io/path: '/metrics'
              prometheus.io/port: '5000'
        spec:
            containers:
            - name: prometheus-tst-reporter
              image: luciantin/prometheus-tst-reporter
              imagePullPolicy: Always
              ports:
                - containerPort: 5000
